/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: TExL0PYah1vLmeZAyOipr/ldyuiNEAePXGBpL5ApMeM8xOdUZUf8PQo53XPt2K7WdK/OFPXdr4kbAhuXH5sVBA==
 */

/* eslint-disable */
// tslint:disable

interface CapabilityData {
  book: string
  description: string
  fields: (any) | null
  /**
   * @default nextval('ptu_05.capability_data_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'capability_data_id'}
  image: (string) | null
  name: string
  page_num: number
}
export default CapabilityData;

interface CapabilityData_InsertParameters {
  book: string
  description: string
  fields?: (any) | null
  /**
   * @default nextval('ptu_05.capability_data_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'capability_data_id'}
  image?: (string) | null
  name: string
  page_num: number
}
export type {CapabilityData_InsertParameters}
