/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: thV6nnMSjNlfOdOJasnvozt51cwqaun1rWBGs3IbcPMVb+xYRrOMRGzuM04i2g5Zm++NJsdi0Z1hRS5hvAjX+w==
 */

/* eslint-disable */
// tslint:disable

interface DBData {
  book: string
  page_num: number
  rank: number & {readonly __brand?: 'd_b_data_rank'}
  rolled: string
  set: number
}
export default DBData;

interface DBData_InsertParameters {
  book: string
  page_num: number
  rank: number & {readonly __brand?: 'd_b_data_rank'}
  rolled: string
  set: number
}
export type {DBData_InsertParameters}
