/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: zrGFJzIvGZAo7yMIt/xJrYSZCTjDhix8be4ferLqBOJL1hiuKF0KMmX5AStXKfaVYlj3qxMeQ0ySN76/m15R2w==
 */

/* eslint-disable */
// tslint:disable

interface ItemData {
  book: string
  cost: (string) | null
  description: string
  /**
   * @default nextval('ptu_05.item_data_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'item_data_id'}
  modifier: (string) | null
  name: string
  page_num: string
  slot: (string) | null
}
export default ItemData;

interface ItemData_InsertParameters {
  book: string
  cost?: (string) | null
  description: string
  /**
   * @default nextval('ptu_05.item_data_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'item_data_id'}
  modifier?: (string) | null
  name: string
  page_num: string
  slot?: (string) | null
}
export type {ItemData_InsertParameters}
