/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: dtGdJ3UW1XZALydco/o+UTAw5KGdl1ZkNKdJcgWBIS9Wk/s48DY8kKk8VhbErFNbjOb+Cq+DGTHRA9yGa4/MiQ==
 */

/* eslint-disable */
// tslint:disable

interface KeywordData {
  book: string
  description: string
  /**
   * @default nextval('ptu_05.keyword_data_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'keyword_data_id'}
  image: (string) | null
  is_weather: boolean
  name: string
  page_num: number
}
export default KeywordData;

interface KeywordData_InsertParameters {
  book: string
  description: string
  /**
   * @default nextval('ptu_05.keyword_data_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'keyword_data_id'}
  image?: (string) | null
  is_weather: boolean
  name: string
  page_num: number
}
export type {KeywordData_InsertParameters}
