/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: K1yWvGIXPceK2NcHay6IWVbcTxqN3KYJBhV01tE98MThS23AXk4P3gqPoZGP5mxLNmTfEutR2YAbFfhZuJGdWw==
 */

/* eslint-disable */
// tslint:disable

interface MonNature {
  embed: any
  id: string & {readonly __brand?: 'mon_nature_id'}
}
export default MonNature;

interface MonNature_InsertParameters {
  embed: any
  id: string & {readonly __brand?: 'mon_nature_id'}
}
export type {MonNature_InsertParameters}
