/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: xcmhoBdSvsyvYrZ6+u0zKjMz/+1BWyh5ucG2vMfD7ntd6ep0Q5DIcOm3cT5fGmuEuF6TuWbqtEPf7wbLoDUJlg==
 */

/* eslint-disable */
// tslint:disable

interface Move {
  embed: any
  id: string & {readonly __brand?: 'move_id'}
}
export default Move;

interface Move_InsertParameters {
  embed: any
  id: string & {readonly __brand?: 'move_id'}
}
export type {Move_InsertParameters}
