/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: XtRBt61zE51FtjcfVwRuh9VR9N+OoaCZVQkLH2RINMLATLTNQvdWwB6T1k968IgfmLqRfrR4yieBUnbJAEkF9g==
 */

/* eslint-disable */
// tslint:disable

interface Schema {
  id: string & {readonly __brand?: 'schema_id'}
  schema: any
}
export default Schema;

interface Schema_InsertParameters {
  id: string & {readonly __brand?: 'schema_id'}
  schema: any
}
export type {Schema_InsertParameters}
