/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: yrVt/sckh9hTO+urXssysXRhkEsikzrmmL4R5WpuH7/GjBSS8yrSods06T3J3uj9DkwnoP7zcdiJ9sHp6/6RMQ==
 */

/* eslint-disable */
// tslint:disable

interface AbilityData {
  bonus: (string) | null
  book: string
  effect: string
  frequency: string
  /**
   * @default nextval('ptu_pt.ability_data_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'ability_data_id'}
  keywords: (string) | null
  name: string
  page_num: number
  target: (string) | null
  trigger: (string) | null
}
export default AbilityData;

interface AbilityData_InsertParameters {
  bonus?: (string) | null
  book: string
  effect: string
  frequency: string
  /**
   * @default nextval('ptu_pt.ability_data_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'ability_data_id'}
  keywords?: (string) | null
  name: string
  page_num: number
  target?: (string) | null
  trigger?: (string) | null
}
export type {AbilityData_InsertParameters}
