/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: IT1IGEG0Q4qcrW+RIwDb9Hyc/nl98MeQv5AHp0txVMH3T2NjcxelGQ1EgjwYkEjRPZjzQbYRUlvI4u+Fhq2ltw==
 */

/* eslint-disable */
// tslint:disable

interface AmbiguiousNames {
  name: string & {readonly __brand?: 'ambiguious_names_name'}
}
export default AmbiguiousNames;

interface AmbiguiousNames_InsertParameters {
  name: string & {readonly __brand?: 'ambiguious_names_name'}
}
export type {AmbiguiousNames_InsertParameters}
