/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: T4/60Gld9L/rdEO/IhJHfNlH+RS5XiCxT4izP3qhJLk9qvTH2dD2fXfYtwlteG1GxT6f0QAFLijUJvhHbKybpw==
 */

/* eslint-disable */
// tslint:disable

interface DeletedAbilities {
  name: string & {readonly __brand?: 'deleted_abilities_name'}
}
export default DeletedAbilities;

interface DeletedAbilities_InsertParameters {
  name: string & {readonly __brand?: 'deleted_abilities_name'}
}
export type {DeletedAbilities_InsertParameters}
