/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 9Rqv8lB8M1TMBS3HIx09mFSoXKuj2OQZuMnNkJD3FpDOmyeh+h3IRjZGN7PT6Lkr6LzZ98CXin3gST3bcGpK6g==
 */

/* eslint-disable */
// tslint:disable

interface EdgeData {
  book: string
  effect: string
  frequency: (string) | null
  /**
   * @default nextval('ptu_pt.edge_data_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'edge_data_id'}
  name: string
  page_num: number
  prerequisites: (string) | null
}
export default EdgeData;

interface EdgeData_InsertParameters {
  book: string
  effect: string
  frequency?: (string) | null
  /**
   * @default nextval('ptu_pt.edge_data_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'edge_data_id'}
  name: string
  page_num: number
  prerequisites?: (string) | null
}
export type {EdgeData_InsertParameters}
