/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: JaVM7HkX8RWAu3kqruR7DmpHb9OTDAkniP3g6Bb9dmVI/hvPBj4Vdsf37T8LjnJiLjOiUkd/V+KbJW10J/t8nQ==
 */

/* eslint-disable */
// tslint:disable

interface Feature {
  embed: any
  id: string & {readonly __brand?: 'feature_id'}
}
export default Feature;

interface Feature_InsertParameters {
  embed: any
  id: string & {readonly __brand?: 'feature_id'}
}
export type {Feature_InsertParameters}
