/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: Due6iiFElNDl2dbVQhvVTXinCV6eixhmxcoGJhda0A0ZvG/ftRLTKUc2yUYSay5C3kHgo+kFHLa8xCJjNaplsA==
 */

/* eslint-disable */
// tslint:disable

import AbilityData, {AbilityData_InsertParameters} from './ability_data'
import AmbiguiousNames, {AmbiguiousNames_InsertParameters} from './ambiguious_names'
import CapabilityData, {CapabilityData_InsertParameters} from './capability_data'
import DeletedAbilities, {DeletedAbilities_InsertParameters} from './deleted_abilities'
import EdgeData, {EdgeData_InsertParameters} from './edge_data'
import Feature, {Feature_InsertParameters} from './feature'
import ItemData, {ItemData_InsertParameters} from './item_data'
import List, {List_InsertParameters} from './list'
import Maneuver, {Maneuver_InsertParameters} from './maneuver'
import Minifeat, {Minifeat_InsertParameters} from './minifeat'
import MonNature, {MonNature_InsertParameters} from './mon_nature'
import Move, {Move_InsertParameters} from './move'
import Pokeedge, {Pokeedge_InsertParameters} from './pokeedge'
import Pokemon, {Pokemon_InsertParameters} from './pokemon'
import Schema, {Schema_InsertParameters} from './schema'
import Status, {Status_InsertParameters} from './status'

interface DatabaseSchema {
  ability_data: {record: AbilityData, insert: AbilityData_InsertParameters};
  ambiguious_names: {record: AmbiguiousNames, insert: AmbiguiousNames_InsertParameters};
  capability_data: {record: CapabilityData, insert: CapabilityData_InsertParameters};
  deleted_abilities: {record: DeletedAbilities, insert: DeletedAbilities_InsertParameters};
  edge_data: {record: EdgeData, insert: EdgeData_InsertParameters};
  feature: {record: Feature, insert: Feature_InsertParameters};
  item_data: {record: ItemData, insert: ItemData_InsertParameters};
  list: {record: List, insert: List_InsertParameters};
  maneuver: {record: Maneuver, insert: Maneuver_InsertParameters};
  minifeat: {record: Minifeat, insert: Minifeat_InsertParameters};
  mon_nature: {record: MonNature, insert: MonNature_InsertParameters};
  move: {record: Move, insert: Move_InsertParameters};
  pokeedge: {record: Pokeedge, insert: Pokeedge_InsertParameters};
  pokemon: {record: Pokemon, insert: Pokemon_InsertParameters};
  schema: {record: Schema, insert: Schema_InsertParameters};
  status: {record: Status, insert: Status_InsertParameters};
}
export default DatabaseSchema;

/**
 * JSON serialize values (v) if the table name (t) and column name (c)
 * is a JSON or JSONB column.
 * This is necessary if you want to store values that are not plain objects
 * in a JSON or JSONB column.
 */
function serializeValue(t: string, c: string, v: unknown): unknown {
  if (
    (t === "capability_data" && c === "fields") ||
    (t === "feature" && c === "embed") ||
    (t === "list" && c === "embed") ||
    (t === "maneuver" && c === "embed") ||
    (t === "minifeat" && c === "embed") ||
    (t === "mon_nature" && c === "embed") ||
    (t === "move" && c === "embed") ||
    (t === "pokeedge" && c === "embed") ||
    (t === "pokemon" && c === "embed") ||
    (t === "schema" && c === "schema") ||
    (t === "status" && c === "embed")
  ) {
    return JSON.stringify(v);
  }
  return v;
}
export {serializeValue}

export type {
  AbilityData,
  AbilityData_InsertParameters,
  AmbiguiousNames,
  AmbiguiousNames_InsertParameters,
  CapabilityData,
  CapabilityData_InsertParameters,
  DeletedAbilities,
  DeletedAbilities_InsertParameters,
  EdgeData,
  EdgeData_InsertParameters,
  Feature,
  Feature_InsertParameters,
  ItemData,
  ItemData_InsertParameters,
  List,
  List_InsertParameters,
  Maneuver,
  Maneuver_InsertParameters,
  Minifeat,
  Minifeat_InsertParameters,
  MonNature,
  MonNature_InsertParameters,
  Move,
  Move_InsertParameters,
  Pokeedge,
  Pokeedge_InsertParameters,
  Pokemon,
  Pokemon_InsertParameters,
  Schema,
  Schema_InsertParameters,
  Status,
  Status_InsertParameters,
}
