/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: eIPgqC7SiUGPLeH7liL6lAxFSz/rqo/CX1oqgUYD4Uka5a2X5Q8F/zSn1BF2YrDkJ2R7Fp1d/Exde16TbeZgFQ==
 */

/* eslint-disable */
// tslint:disable

interface Item {
  embed: any
  id: string & {readonly __brand?: 'item_id'}
}
export default Item;

interface Item_InsertParameters {
  embed: any
  id: string & {readonly __brand?: 'item_id'}
}
export type {Item_InsertParameters}
