/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 0nBrIXNW3b9K7rbKVPBmtTvt073P3DkLoWdPyuyCzouWmKP/XOgByKq1aZdbbOci5uqqCxK08splyX6AhUBFlg==
 */

/* eslint-disable */
// tslint:disable

interface Minifeat {
  embed: any
  id: string & {readonly __brand?: 'minifeat_id'}
}
export default Minifeat;

interface Minifeat_InsertParameters {
  embed: any
  id: string & {readonly __brand?: 'minifeat_id'}
}
export type {Minifeat_InsertParameters}
