/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: fv3VGaxgJwrZUmXzXMTgErT+9ZwL3dp7Ap/2venZzQMV4IMpqjlnOQ/hoRKqT+YlgorpElk7FAjRVSuSf430yQ==
 */

/* eslint-disable */
// tslint:disable

interface Pokemon {
  embed: any
  id: string & {readonly __brand?: 'pokemon_id'}
}
export default Pokemon;

interface Pokemon_InsertParameters {
  embed: any
  id: string & {readonly __brand?: 'pokemon_id'}
}
export type {Pokemon_InsertParameters}
