/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: pbbSZOcpotBO5QIV0cW66kLOBQJUwUjM4tFIUZFRo/r8AP61qZ4AD6dWmflH69hnno8eA9BukuB7lz3xsLLi/A==
 */

/* eslint-disable */
// tslint:disable

import CodexList from './codex_list'

interface Channels {
  channel_id: string & {readonly __brand?: 'channels_channel_id'}
  charseps: (Array<string | null>) | null
  charsigns: (Array<string | null>) | null
  codex: (CodexList['id']) | null
  ephemeral: (boolean) | null
  freeze_on_timeout: (boolean) | null
  inline: (boolean) | null
  server_id: string & {readonly __brand?: 'channels_server_id'}
}
export default Channels;

interface Channels_InsertParameters {
  channel_id: string & {readonly __brand?: 'channels_channel_id'}
  charseps?: (Array<string | null>) | null
  charsigns?: (Array<string | null>) | null
  codex?: (CodexList['id']) | null
  ephemeral?: (boolean) | null
  freeze_on_timeout?: (boolean) | null
  inline?: (boolean) | null
  server_id: string & {readonly __brand?: 'channels_server_id'}
}
export type {Channels_InsertParameters}
