/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: xOLa4FuoAHg1pHZDsnqizdciMG68suv6ihK9t5e0yT0srYb/Awd/QbhMKNI/EfaCge8PdVs5T7VvUxhB8pt01g==
 */

/* eslint-disable */
// tslint:disable

interface CharacterAttributes {
  character_id: number & {readonly __brand?: 'character_attributes_character_id'}
  name: string & {readonly __brand?: 'character_attributes_name'}
  value: string
}
export default CharacterAttributes;

interface CharacterAttributes_InsertParameters {
  character_id: number & {readonly __brand?: 'character_attributes_character_id'}
  name: string & {readonly __brand?: 'character_attributes_name'}
  value: string
}
export type {CharacterAttributes_InsertParameters}
