/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 7BaJoGK87C1KzhY3Pdt0keUVG6tXOMx7JHXJD20RxM6fj7wqrKkJK6+vyLoaK+hh2G9TFH5U5cfNqS2/qBr+QQ==
 */

/* eslint-disable */
// tslint:disable

interface CodexList {
  display_name: string
  /**
   * @default nextval('codex_list_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'codex_list_id'}
}
export default CodexList;

interface CodexList_InsertParameters {
  display_name: string
  /**
   * @default nextval('codex_list_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'codex_list_id'}
}
export type {CodexList_InsertParameters}
