/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: mtiMWi2aR3orurZaw9fNEz3Rym3rGfCrQCyLT9XwWZrxLYF1OngG0KvWTQpc6usMkeEQEoqyqZkGyzYDVJwRDA==
 */

/* eslint-disable */
// tslint:disable

interface CodexList {
  display_name: string
  /**
   * @default nextval('codex_list_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'codex_list_id'}
  prefix: string
}
export default CodexList;

interface CodexList_InsertParameters {
  display_name: string
  /**
   * @default nextval('codex_list_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'codex_list_id'}
  prefix: string
}
export type {CodexList_InsertParameters}
