/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 2d4bTm3PeUJJS2MXIaQZ9QiSgJSM7JyJXIb9iNickAkNJrcRCixpwkS3YXH2oVKhxIpnZSEnO0LAwzTbfEMwlQ==
 */

/* eslint-disable */
// tslint:disable

interface CommandUsage {
  name: string & {readonly __brand?: 'command_usage_name'}
  uses: string
}
export default CommandUsage;

interface CommandUsage_InsertParameters {
  name: string & {readonly __brand?: 'command_usage_name'}
  uses: string
}
export type {CommandUsage_InsertParameters}
