/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: x79H2D2EJlUSRI6y28+n+IfObz4EN/jxEOzEN+pR5h2Xs2FuC9NRH7LXtIYylx80nUePV/EIG8uWy/WhTiBCrA==
 */

/* eslint-disable */
// tslint:disable

import Channels, {Channels_InsertParameters} from './channels'
import CodexList, {CodexList_InsertParameters} from './codex_list'
import ServerModRoles, {ServerModRoles_InsertParameters} from './server_mod_roles'
import Servers, {Servers_InsertParameters} from './servers'

interface DatabaseSchema {
  channels: {record: Channels, insert: Channels_InsertParameters};
  codex_list: {record: CodexList, insert: CodexList_InsertParameters};
  server_mod_roles: {record: ServerModRoles, insert: ServerModRoles_InsertParameters};
  servers: {record: Servers, insert: Servers_InsertParameters};
}
export default DatabaseSchema;

function serializeValue(_tableName: string, _columnName: string, value: unknown): unknown {
  return value;
}
export {serializeValue}
