/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 5f4JH9NZjPvi9jbBQW0Kx4gg6efGr4HIh6W7VUoCXEtzMEMFLqpQcScOI7DR/v0gCEkJzfWwPJX3zAQUUbmU1w==
 */

/* eslint-disable */
// tslint:disable

import Channels, {Channels_InsertParameters} from './channels'
import CharacterAttributes, {CharacterAttributes_InsertParameters} from './character_attributes'
import Characters, {Characters_InsertParameters} from './characters'
import CodexList, {CodexList_InsertParameters} from './codex_list'
import ServerModRoles, {ServerModRoles_InsertParameters} from './server_mod_roles'
import Servers, {Servers_InsertParameters} from './servers'

interface DatabaseSchema {
  channels: {record: Channels, insert: Channels_InsertParameters};
  character_attributes: {record: CharacterAttributes, insert: CharacterAttributes_InsertParameters};
  characters: {record: Characters, insert: Characters_InsertParameters};
  codex_list: {record: CodexList, insert: CodexList_InsertParameters};
  server_mod_roles: {record: ServerModRoles, insert: ServerModRoles_InsertParameters};
  servers: {record: Servers, insert: Servers_InsertParameters};
}
export default DatabaseSchema;

function serializeValue(_tableName: string, _columnName: string, value: unknown): unknown {
  return value;
}
export {serializeValue}
