/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: uS4qQx1DwgC5y6fvFRLFcCjUI7j0+lOtOCbY4cUWcIDncBAHs2bxSB9bUlm+t5VXrOvKTSHNwWVzWitITVxwCA==
 */

/* eslint-disable */
// tslint:disable

import Channels, {Channels_InsertParameters} from './channels'
import CharacterAttributes, {CharacterAttributes_InsertParameters} from './character_attributes'
import Characters, {Characters_InsertParameters} from './characters'
import CodexList, {CodexList_InsertParameters} from './codex_list'
import CommandUsage, {CommandUsage_InsertParameters} from './command_usage'
import ServerModRoles, {ServerModRoles_InsertParameters} from './server_mod_roles'
import Servers, {Servers_InsertParameters} from './servers'
import UniqueServers, {UniqueServers_InsertParameters} from './unique_servers'
import UniqueUsers, {UniqueUsers_InsertParameters} from './unique_users'

interface DatabaseSchema {
  channels: {record: Channels, insert: Channels_InsertParameters};
  character_attributes: {record: CharacterAttributes, insert: CharacterAttributes_InsertParameters};
  characters: {record: Characters, insert: Characters_InsertParameters};
  codex_list: {record: CodexList, insert: CodexList_InsertParameters};
  command_usage: {record: CommandUsage, insert: CommandUsage_InsertParameters};
  server_mod_roles: {record: ServerModRoles, insert: ServerModRoles_InsertParameters};
  servers: {record: Servers, insert: Servers_InsertParameters};
  unique_servers: {record: UniqueServers, insert: UniqueServers_InsertParameters};
  unique_users: {record: UniqueUsers, insert: UniqueUsers_InsertParameters};
}
export default DatabaseSchema;

function serializeValue(_tableName: string, _columnName: string, value: unknown): unknown {
  return value;
}
export {serializeValue}

export type {
  CodexList,
  CodexList_InsertParameters,
  Channels,
  Channels_InsertParameters,
  CharacterAttributes,
  CharacterAttributes_InsertParameters,
  Characters,
  Characters_InsertParameters,
  CommandUsage,
  CommandUsage_InsertParameters,
  ServerModRoles,
  ServerModRoles_InsertParameters,
  Servers,
  Servers_InsertParameters,
  UniqueServers,
  UniqueServers_InsertParameters,
  UniqueUsers,
  UniqueUsers_InsertParameters,
}
