/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: ciioOtQcKhSIX2GeG1NpRmnSTI/yvY5vzMUIPl3IUe3iR7rW4re+YQbV7bOmmNXP/osoiMvI9DgZmD2U74QCyg==
 */

/* eslint-disable */
// tslint:disable

import CodexList from './codex_list'

interface Servers {
  charseps: (Array<string | null>) | null
  charsigns: (Array<string | null>) | null
  codex: (CodexList['id']) | null
  ephemeral: (boolean) | null
  freeze_on_timeout: (boolean) | null
  inline: (boolean) | null
  server_id: string & {readonly __brand?: 'servers_server_id'}
}
export default Servers;

interface Servers_InsertParameters {
  charseps?: (Array<string | null>) | null
  charsigns?: (Array<string | null>) | null
  codex?: (CodexList['id']) | null
  ephemeral?: (boolean) | null
  freeze_on_timeout?: (boolean) | null
  inline?: (boolean) | null
  server_id: string & {readonly __brand?: 'servers_server_id'}
}
export type {Servers_InsertParameters}
