/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: OGQJWS0FU2Xs8cj6S6N5ygWsrKYFD63inh2GOkxNVn7XNUxMYrY4ncvkLOHEqcZF2EKWeNr4Pcel7lOCCT4/rg==
 */

/* eslint-disable */
// tslint:disable

interface ServerModRoles {
  role_id: string & {readonly __brand?: 'server_mod_roles_role_id'}
  server_id: string & {readonly __brand?: 'server_mod_roles_server_id'}
}
export default ServerModRoles;

interface ServerModRoles_InsertParameters {
  role_id: string & {readonly __brand?: 'server_mod_roles_role_id'}
  server_id: string & {readonly __brand?: 'server_mod_roles_server_id'}
}
export type {ServerModRoles_InsertParameters}
