/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: vWRfDYgTQHmkOWd4OTBB3y66DxtLwvhpuetDVQXythvwOiVAyTtys7oOyy/LesNoBGK0ejg8Vq/Afp2KQOvAFA==
 */

/* eslint-disable */
// tslint:disable

interface UniqueServers {
  server_id: string & {readonly __brand?: 'unique_servers_server_id'}
}
export default UniqueServers;

interface UniqueServers_InsertParameters {
  server_id: string & {readonly __brand?: 'unique_servers_server_id'}
}
export type {UniqueServers_InsertParameters}
