/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: vehQzs4MjU3SAQupbXoQPBMuRyp7LRMfHzYpqIQShCfhX98w903MGM36TStiphrgH5/18P+u5P86+8tiucUJtg==
 */

/* eslint-disable */
// tslint:disable

interface UniqueUsers {
  user_id: string & {readonly __brand?: 'unique_users_user_id'}
}
export default UniqueUsers;

interface UniqueUsers_InsertParameters {
  user_id: string & {readonly __brand?: 'unique_users_user_id'}
}
export type {UniqueUsers_InsertParameters}
