/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: wUgnV+6tmGF/hj/xZcCr/vHUKU5fZ2uhcc0mRCPVvI0ZnACvNMeXb4IXEeu7HlQwkOPuT3F1lbIkQRxaKdIAag==
 */

/* eslint-disable */
// tslint:disable

import SystemData, {SystemData_InsertParameters} from './system_data'

interface DatabaseSchema {
  system_data: {record: SystemData, insert: SystemData_InsertParameters};
}
export default DatabaseSchema;

function serializeValue(_tableName: string, _columnName: string, value: unknown): unknown {
  return value;
}
export {serializeValue}

export type {
  SystemData,
  SystemData_InsertParameters,
}
