/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: /k7vu7t8Gvqwwgwgin2HBZlrvrDztF6hNjxm9gYIL54TSKRZCHL64lt0g2Fxf6QfTRfTOb0vmhQrtnowoK4YMA==
 */

/* eslint-disable */
// tslint:disable

interface SystemData {
  name: string
  system: string
}
export default SystemData;

interface SystemData_InsertParameters {
  name: string
  system: string
}
export type {SystemData_InsertParameters}
