/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: wVWK4y6d71NGn3UPF2p7TbhGa/VQoZZBmo7tnRzyfj6XgVq4mt3v5xnF7q0bddyL4I4QaooYT5ajajt9uN2hCg==
 */

/* eslint-disable */
// tslint:disable

interface AbilityData {
  bonus: (string) | null
  book: string
  effect: string
  frequency: string
  /**
   * @default nextval('ptu_al.ability_data_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'ability_data_id'}
  keywords: (string) | null
  name: string
  note: (string) | null
  page_num: number
  special: (string) | null
  target: (string) | null
  trigger: (string) | null
}
export default AbilityData;

interface AbilityData_InsertParameters {
  bonus?: (string) | null
  book: string
  effect: string
  frequency: string
  /**
   * @default nextval('ptu_al.ability_data_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'ability_data_id'}
  keywords?: (string) | null
  name: string
  note?: (string) | null
  page_num: number
  special?: (string) | null
  target?: (string) | null
  trigger?: (string) | null
}
export type {AbilityData_InsertParameters}
