/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: SGRInc6krhL05AOa0g3Fh6ACR7INsNPTfMBUJc4+83CVRWoDs5IVQhkcDgRDQlNRuiwmN7jCBVNvzgStvsPpFg==
 */

/* eslint-disable */
// tslint:disable

interface CapabilityData {
  book: string
  description: string
  fields: (any) | null
  /**
   * @default nextval('ptu_al.capability_data_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'capability_data_id'}
  image: (string) | null
  name: string
  page_num: number
}
export default CapabilityData;

interface CapabilityData_InsertParameters {
  book: string
  description: string
  fields?: (any) | null
  /**
   * @default nextval('ptu_al.capability_data_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'capability_data_id'}
  image?: (string) | null
  name: string
  page_num: number
}
export type {CapabilityData_InsertParameters}
