/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 6IGUKMYzhfnJtMOwHLXUaPjI4G+KCV0aRFo6yLmpYSxhzBcCAiufYU0hCj7uOljIIWEt4wQ69t8ZVCde5iiCKA==
 */

/* eslint-disable */
// tslint:disable

interface Maneuver {
  embed: any
  id: string & {readonly __brand?: 'maneuver_id'}
}
export default Maneuver;

interface Maneuver_InsertParameters {
  embed: any
  id: string & {readonly __brand?: 'maneuver_id'}
}
export type {Maneuver_InsertParameters}
