/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: B8kQQRlGi/00ZUHsvn1Mwp6/WUyT28FJAXVKAi2Vexw8HdX1Q7JXCcd8wBqP4cIJeC3v0bm2DpQlxa+yuiiDJg==
 */

/* eslint-disable */
// tslint:disable

interface Pokeedge {
  embed: any
  id: string & {readonly __brand?: 'pokeedge_id'}
}
export default Pokeedge;

interface Pokeedge_InsertParameters {
  embed: any
  id: string & {readonly __brand?: 'pokeedge_id'}
}
export type {Pokeedge_InsertParameters}
