/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: TXcEODht92M66DW484hFJjYmRP91qzv4JR4OrtM3aYm5CLugLXgFkn7sTjVpGQ0jHarmrjPumWpL3Jf8Vb51eQ==
 */

/* eslint-disable */
// tslint:disable

interface AbilityData {
  bonus: (string) | null
  book: string
  effect: string
  frequency: string
  /**
   * @default nextval('ptu_hi.ability_data_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'ability_data_id'}
  image: (string) | null
  keywords: (string) | null
  name: string
  note: (string) | null
  page_num: number
  special: (string) | null
  target: (string) | null
  trigger: (string) | null
}
export default AbilityData;

interface AbilityData_InsertParameters {
  bonus?: (string) | null
  book: string
  effect: string
  frequency: string
  /**
   * @default nextval('ptu_hi.ability_data_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'ability_data_id'}
  image?: (string) | null
  keywords?: (string) | null
  name: string
  note?: (string) | null
  page_num: number
  special?: (string) | null
  target?: (string) | null
  trigger?: (string) | null
}
export type {AbilityData_InsertParameters}
