/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 3Ehw4D1CH35F7yjWv+GgHxPWzvEXthYQ8W67Emk23eFFp1Ak9rnhNOqrWlZ3DpxTa1uj9BIX1bdg4V42hmP34Q==
 */

/* eslint-disable */
// tslint:disable

import AbilityData, {AbilityData_InsertParameters} from './ability_data'
import NewMove, {NewMove_InsertParameters} from './new_move'
import Pokemon, {Pokemon_InsertParameters} from './pokemon'
import Schema, {Schema_InsertParameters} from './schema'

interface DatabaseSchema {
  ability_data: {record: AbilityData, insert: AbilityData_InsertParameters};
  new_move: {record: NewMove, insert: NewMove_InsertParameters};
  pokemon: {record: Pokemon, insert: Pokemon_InsertParameters};
  schema: {record: Schema, insert: Schema_InsertParameters};
}
export default DatabaseSchema;

/**
 * JSON serialize values (v) if the table name (t) and column name (c)
 * is a JSON or JSONB column.
 * This is necessary if you want to store values that are not plain objects
 * in a JSON or JSONB column.
 */
function serializeValue(t: string, c: string, v: unknown): unknown {
  if (
    (t === "new_move" && c === "embed") ||
    (t === "pokemon" && c === "embed") ||
    (t === "schema" && c === "schema")
  ) {
    return JSON.stringify(v);
  }
  return v;
}
export {serializeValue}

export type {
  AbilityData,
  AbilityData_InsertParameters,
  NewMove,
  NewMove_InsertParameters,
  Pokemon,
  Pokemon_InsertParameters,
  Schema,
  Schema_InsertParameters,
}
