/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 2D6x6mBprv8tQnF3oWe5qNribXh5AC76BeFf+6FiXxKbdmnIrD9KgjpJrbZA7Rv00tVBBTEQrJB8yaJYserxSg==
 */

/* eslint-disable */
// tslint:disable

interface NewMove {
  embed: any
  id: string & {readonly __brand?: 'new_move_id'}
}
export default NewMove;

interface NewMove_InsertParameters {
  embed: any
  id: string & {readonly __brand?: 'new_move_id'}
}
export type {NewMove_InsertParameters}
