/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: x/z7YMn7zUe/fQ+7vVoNfxcr7ason2xdgfxvWdGDsdE0oIFbiQ6alXRrfCHwO/oB0wJQH2WDVJzg8/4rH6J7ng==
 */

/* eslint-disable */
// tslint:disable

interface CapabilityData {
  book: string
  description: string
  fields: (any) | null
  /**
   * @default nextval('ptu_ga.capability_data_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'capability_data_id'}
  image: (string) | null
  name: string
  page_num: number
}
export default CapabilityData;

interface CapabilityData_InsertParameters {
  book: string
  description: string
  fields?: (any) | null
  /**
   * @default nextval('ptu_ga.capability_data_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'capability_data_id'}
  image?: (string) | null
  name: string
  page_num: number
}
export type {CapabilityData_InsertParameters}
