/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: v4husUBlx0L71gGYPjgU4UBHiadS4dyfQMZvmvaGe0HFVditZeOutXnafRskg+E7jqjd9jPR92Ko2BYNdRf5Sg==
 */

/* eslint-disable */
// tslint:disable

interface Keyword {
  embed: any
  id: string & {readonly __brand?: 'keyword_id'}
}
export default Keyword;

interface Keyword_InsertParameters {
  embed: any
  id: string & {readonly __brand?: 'keyword_id'}
}
export type {Keyword_InsertParameters}
