/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 5hT19+6mFf2nDz6MBOj4Olb6Och4kmLUZ2i9efPNBJI7zrkfQ6N5R8zY8CqPJ6pyZ7JSiOT3Wuz52fy0UwPffA==
 */

/* eslint-disable */
// tslint:disable

interface AbilityPassive {
  book: string
  effect: string
  /**
   * @default nextval('pta_03.ability_passive_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'ability_passive_id'}
  name: string
  page_num: number
}
export default AbilityPassive;

interface AbilityPassive_InsertParameters {
  book: string
  effect: string
  /**
   * @default nextval('pta_03.ability_passive_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'ability_passive_id'}
  name: string
  page_num: number
}
export type {AbilityPassive_InsertParameters}
