/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: Kf70tGfqM84UFnyGCz10uNNm3PEOJB9cs9+Bq3GZE50h0yfskkJoKrHdN5BOMeZbUnvKRQbD9th116gopnffIA==
 */

/* eslint-disable */
// tslint:disable

import AbilityPassive, {AbilityPassive_InsertParameters} from './ability_passive'
import LegPassiveData, {LegPassiveData_InsertParameters} from './leg_passive_data'
import LegSkillData, {LegSkillData_InsertParameters} from './leg_skill_data'
import MoveData, {MoveData_InsertParameters} from './move_data'
import PokemonAbilityPassives, {PokemonAbilityPassives_InsertParameters} from './pokemon_ability_passives'
import PokemonBase, {PokemonBase_InsertParameters} from './pokemon_base'
import PokemonDyna, {PokemonDyna_InsertParameters} from './pokemon_dyna'
import PokemonLegPassives, {PokemonLegPassives_InsertParameters} from './pokemon_leg_passives'
import PokemonLegSkills, {PokemonLegSkills_InsertParameters} from './pokemon_leg_skills'
import PokemonMega, {PokemonMega_InsertParameters} from './pokemon_mega'
import PokemonMegaMoves, {PokemonMegaMoves_InsertParameters} from './pokemon_mega_moves'
import PokemonMegaSkills, {PokemonMegaSkills_InsertParameters} from './pokemon_mega_skills'
import PokemonMoves, {PokemonMoves_InsertParameters} from './pokemon_moves'
import PokemonProfs, {PokemonProfs_InsertParameters} from './pokemon_profs'
import PokemonSkills, {PokemonSkills_InsertParameters} from './pokemon_skills'
import PokemonStatPassives, {PokemonStatPassives_InsertParameters} from './pokemon_stat_passives'
import Schema, {Schema_InsertParameters} from './schema'
import SkillData, {SkillData_InsertParameters} from './skill_data'
import StatPassive, {StatPassive_InsertParameters} from './stat_passive'

interface DatabaseSchema {
  ability_passive: {record: AbilityPassive, insert: AbilityPassive_InsertParameters};
  leg_passive_data: {record: LegPassiveData, insert: LegPassiveData_InsertParameters};
  leg_skill_data: {record: LegSkillData, insert: LegSkillData_InsertParameters};
  move_data: {record: MoveData, insert: MoveData_InsertParameters};
  pokemon_ability_passives: {record: PokemonAbilityPassives, insert: PokemonAbilityPassives_InsertParameters};
  pokemon_base: {record: PokemonBase, insert: PokemonBase_InsertParameters};
  pokemon_dyna: {record: PokemonDyna, insert: PokemonDyna_InsertParameters};
  pokemon_leg_passives: {record: PokemonLegPassives, insert: PokemonLegPassives_InsertParameters};
  pokemon_leg_skills: {record: PokemonLegSkills, insert: PokemonLegSkills_InsertParameters};
  pokemon_mega: {record: PokemonMega, insert: PokemonMega_InsertParameters};
  pokemon_mega_moves: {record: PokemonMegaMoves, insert: PokemonMegaMoves_InsertParameters};
  pokemon_mega_skills: {record: PokemonMegaSkills, insert: PokemonMegaSkills_InsertParameters};
  pokemon_moves: {record: PokemonMoves, insert: PokemonMoves_InsertParameters};
  pokemon_profs: {record: PokemonProfs, insert: PokemonProfs_InsertParameters};
  pokemon_skills: {record: PokemonSkills, insert: PokemonSkills_InsertParameters};
  pokemon_stat_passives: {record: PokemonStatPassives, insert: PokemonStatPassives_InsertParameters};
  schema: {record: Schema, insert: Schema_InsertParameters};
  skill_data: {record: SkillData, insert: SkillData_InsertParameters};
  stat_passive: {record: StatPassive, insert: StatPassive_InsertParameters};
}
export default DatabaseSchema;

/**
 * JSON serialize values (v) if the table name (t) and column name (c)
 * is a JSON or JSONB column.
 * This is necessary if you want to store values that are not plain objects
 * in a JSON or JSONB column.
 */
function serializeValue(t: string, c: string, v: unknown): unknown {
  if (t === "schema" && c === "schema") {
    return JSON.stringify(v);
  }
  return v;
}
export {serializeValue}

export type {
  AbilityPassive,
  AbilityPassive_InsertParameters,
  LegPassiveData,
  LegPassiveData_InsertParameters,
  LegSkillData,
  LegSkillData_InsertParameters,
  MoveData,
  MoveData_InsertParameters,
  PokemonAbilityPassives,
  PokemonAbilityPassives_InsertParameters,
  PokemonBase,
  PokemonBase_InsertParameters,
  PokemonDyna,
  PokemonDyna_InsertParameters,
  PokemonLegPassives,
  PokemonLegPassives_InsertParameters,
  PokemonLegSkills,
  PokemonLegSkills_InsertParameters,
  StatPassive,
  StatPassive_InsertParameters,
  PokemonMega,
  PokemonMega_InsertParameters,
  PokemonMegaMoves,
  PokemonMegaMoves_InsertParameters,
  PokemonMegaSkills,
  PokemonMegaSkills_InsertParameters,
  PokemonMoves,
  PokemonMoves_InsertParameters,
  PokemonProfs,
  PokemonProfs_InsertParameters,
  PokemonSkills,
  PokemonSkills_InsertParameters,
  PokemonStatPassives,
  PokemonStatPassives_InsertParameters,
  Schema,
  Schema_InsertParameters,
  SkillData,
  SkillData_InsertParameters,
}
