/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: HDYzx4NruJZM9dDshGwtQXW7lyIkrZ/lUr3xUQ0G/NAB/MtFjhjfgK1X//6d94/oV8osWsU6U+WPehhwQi9gfw==
 */

/* eslint-disable */
// tslint:disable

interface LegSkillData {
  book: string
  effect: string
  frequency: string
  /**
   * @default nextval('pta_03.leg_skill_data_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'leg_skill_data_id'}
  name: string
  page_num: number
}
export default LegSkillData;

interface LegSkillData_InsertParameters {
  book: string
  effect: string
  frequency: string
  /**
   * @default nextval('pta_03.leg_skill_data_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'leg_skill_data_id'}
  name: string
  page_num: number
}
export type {LegSkillData_InsertParameters}
