/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: aamY0pdOtP4f+0RMMRmabvlb/6SyDhnk3dZrZuPJvFTZmegvU1KcN+P56qpxrh7TuQpgw1P2upKlenCQg5e+Yg==
 */

/* eslint-disable */
// tslint:disable

interface LegPassiveData {
  book: string
  effect: string
  /**
   * @default nextval('pta_03.leg_passive_data_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'leg_passive_data_id'}
  name: string
  page_num: number
}
export default LegPassiveData;

interface LegPassiveData_InsertParameters {
  book: string
  effect: string
  /**
   * @default nextval('pta_03.leg_passive_data_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'leg_passive_data_id'}
  name: string
  page_num: number
}
export type {LegPassiveData_InsertParameters}
