/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 192rFui4iqu48CXMo57BAxsU1dIXAHUw2ryb74fud5FxyWEE3nNcntZhN/Rha2dj5aTetqH4Hdgrhf3jzz6biw==
 */

/* eslint-disable */
// tslint:disable

interface PokemonBase {
  attack: number
  book: string
  defense: number
  dex_num: number
  diet: Array<string | null>
  egg_groups: Array<string | null>
  evolutions: Array<string | null>
  habitats: Array<string | null>
  hatch_rate: (number) | null
  hp: number
  /**
   * @default nextval('pta_03.pokemon_base_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'pokemon_base_id'}
  name: string
  page_num: number
  rarity: string
  size_class: string
  sp_attack: number
  sp_defense: number
  speed: number
  types: Array<string | null>
  weight_class: string
}
export default PokemonBase;

interface PokemonBase_InsertParameters {
  attack: number
  book: string
  defense: number
  dex_num: number
  diet: Array<string | null>
  egg_groups: Array<string | null>
  evolutions: Array<string | null>
  habitats: Array<string | null>
  hatch_rate?: (number) | null
  hp: number
  /**
   * @default nextval('pta_03.pokemon_base_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'pokemon_base_id'}
  name: string
  page_num: number
  rarity: string
  size_class: string
  sp_attack: number
  sp_defense: number
  speed: number
  types: Array<string | null>
  weight_class: string
}
export type {PokemonBase_InsertParameters}
