/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: EVWd48IGP4fDVrJNwMKvBs4URhEgisg4X/K0tXyyHH5k/azeeSJWc1BLB1NAc60eTgxIEnXlaFnHx+WXzZoDvQ==
 */

/* eslint-disable */
// tslint:disable

import LegSkillData from './leg_skill_data'

interface PokemonLegSkills {
  leg_skill_id: LegSkillData['id']
  pokemon_id: number & {readonly __brand?: 'pokemon_leg_skills_pokemon_id'}
}
export default PokemonLegSkills;

interface PokemonLegSkills_InsertParameters {
  leg_skill_id: LegSkillData['id']
  pokemon_id: number & {readonly __brand?: 'pokemon_leg_skills_pokemon_id'}
}
export type {PokemonLegSkills_InsertParameters}
