/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: LLu+KlABvz8zEOUybshAviX6qfU/qUey3BDt21NjLN8a6xBAkatT/WGvMdi+bwhpIOXpCiC1iXK4cZf6zqyKug==
 */

/* eslint-disable */
// tslint:disable

import PokemonBase from './pokemon_base'

interface PokemonEvolutionStage {
  base_pokemon_id: PokemonBase['id']
  line_id: (number) | null
  note: (string) | null
  pokemon_id: number & {readonly __brand?: 'pokemon_evolution_stage_pokemon_id'}
  replace_form_with: (string) | null
  stage_number: number
}
export default PokemonEvolutionStage;

interface PokemonEvolutionStage_InsertParameters {
  base_pokemon_id: PokemonBase['id']
  line_id?: (number) | null
  note?: (string) | null
  pokemon_id: number & {readonly __brand?: 'pokemon_evolution_stage_pokemon_id'}
  replace_form_with?: (string) | null
  stage_number: number
}
export type {PokemonEvolutionStage_InsertParameters}
