/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: DTtiRk5Cb9TFCfC4N0qte8Z2yd3cjrGX6tvoMTXtzxQcsISerRG6Egk62q7LQack8tMqiiHCCvTAATtm4eOBRg==
 */

/* eslint-disable */
// tslint:disable

import PokemonBase from './pokemon_base'

interface PokemonEvolutionStage {
  base_pokemon_id: PokemonBase['id']
  hide_from_pre_evos: (boolean) | null
  line_id: (number) | null
  note: (string) | null
  pokemon_id: number & {readonly __brand?: 'pokemon_evolution_stage_pokemon_id'}
  replace_form_with: (string) | null
  stage_number: number
}
export default PokemonEvolutionStage;

interface PokemonEvolutionStage_InsertParameters {
  base_pokemon_id: PokemonBase['id']
  hide_from_pre_evos?: (boolean) | null
  line_id?: (number) | null
  note?: (string) | null
  pokemon_id: number & {readonly __brand?: 'pokemon_evolution_stage_pokemon_id'}
  replace_form_with?: (string) | null
  stage_number: number
}
export type {PokemonEvolutionStage_InsertParameters}
