/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: iooYBWJ8QJSc1Eqf6zRwIVgZqbOJEG3OyL28ufFSkBVVM48EZKbWD1+nIF+YaRj5BML9EY9fzbyhxb6FWuezCA==
 */

/* eslint-disable */
// tslint:disable

import AbilityPassive from './ability_passive'

interface PokemonAbilityPassives {
  ability_passive_id: AbilityPassive['id']
  effect_override: (string) | null
  pokemon_id: number & {readonly __brand?: 'pokemon_ability_passives_pokemon_id'}
}
export default PokemonAbilityPassives;

interface PokemonAbilityPassives_InsertParameters {
  ability_passive_id: AbilityPassive['id']
  effect_override?: (string) | null
  pokemon_id: number & {readonly __brand?: 'pokemon_ability_passives_pokemon_id'}
}
export type {PokemonAbilityPassives_InsertParameters}
