/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: E31mlJraAHq42u7zrVi9j6lpAOxWKKQOcQ7VcdNQkAtturg53Vs9zgrr+YtC7AGXsqmQMUIJWbP9cU5GE7u6yw==
 */

/* eslint-disable */
// tslint:disable

import MoveData from './move_data'

interface PokemonMoves {
  move_id: MoveData['id']
  pokemon_id: number & {readonly __brand?: 'pokemon_moves_pokemon_id'}
}
export default PokemonMoves;

interface PokemonMoves_InsertParameters {
  move_id: MoveData['id']
  pokemon_id: number & {readonly __brand?: 'pokemon_moves_pokemon_id'}
}
export type {PokemonMoves_InsertParameters}
