/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: JmDgXn9FuXPcqJN1jPZb2x+ci5oXXOZx40zX+tlz2ldl6qsoCTG4pYU8Pv2zIlMUUr127EjQGaZ/sseCjG0f5w==
 */

/* eslint-disable */
// tslint:disable

import PokemonMega from './pokemon_mega'

interface PokemonMegaSkills {
  mega_id: PokemonMega['id']
  skill_id: number & {readonly __brand?: 'pokemon_mega_skills_skill_id'}
}
export default PokemonMegaSkills;

interface PokemonMegaSkills_InsertParameters {
  mega_id: PokemonMega['id']
  skill_id: number & {readonly __brand?: 'pokemon_mega_skills_skill_id'}
}
export type {PokemonMegaSkills_InsertParameters}
