/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 7f2f2KZi5TA7fUn+rNb7rtaN1cpHsJ2uPABRQK5NY0BcEYMGvuubxNgPJLozgIj28eOdB5SI6xKnxshdjrMzfg==
 */

/* eslint-disable */
// tslint:disable

import MoveData from './move_data'

interface PokemonDyna {
  move_id: MoveData['id']
  pokemon_id: number & {readonly __brand?: 'pokemon_dyna_pokemon_id'}
}
export default PokemonDyna;

interface PokemonDyna_InsertParameters {
  move_id: MoveData['id']
  pokemon_id: number & {readonly __brand?: 'pokemon_dyna_pokemon_id'}
}
export type {PokemonDyna_InsertParameters}
