/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: dSa/aUlnhB74tZ9DajXXT6EklyM/KPkLh1sfy9lQePzOcBy0sr+T41uXGb7EULdmDJ7Yr6qMRpzJQtxdudrfMA==
 */

/* eslint-disable */
// tslint:disable

interface PokemonStatPassives {
  pokemon_id: number & {readonly __brand?: 'pokemon_stat_passives_pokemon_id'}
  stat_passive_id: number & {readonly __brand?: 'pokemon_stat_passives_stat_passive_id'}
}
export default PokemonStatPassives;

interface PokemonStatPassives_InsertParameters {
  pokemon_id: number & {readonly __brand?: 'pokemon_stat_passives_pokemon_id'}
  stat_passive_id: number & {readonly __brand?: 'pokemon_stat_passives_stat_passive_id'}
}
export type {PokemonStatPassives_InsertParameters}
