/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: A2EsUghBZwoBhlg1RYubR032L4prYn8W6Ve5O9WwvN1Clw+L/HnlRsKI0yGb74Y2eLUBcHZzGdNrBgaiRJTupA==
 */

/* eslint-disable */
// tslint:disable

interface PokemonProfs {
  pokemon_id: number & {readonly __brand?: 'pokemon_profs_pokemon_id'}
  profs: Array<string | null>
  sigs: Array<string | null>
}
export default PokemonProfs;

interface PokemonProfs_InsertParameters {
  pokemon_id: number & {readonly __brand?: 'pokemon_profs_pokemon_id'}
  profs: Array<string | null>
  sigs: Array<string | null>
}
export type {PokemonProfs_InsertParameters}
