/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: s3cx3nGTgRh0OK5v3rHw4ejG2iBuYBp58CLVUnfQ6/sRx5U6iYnniC7RuLORH5wYO9Ykd4WHI43aNGbp3oL6XQ==
 */

/* eslint-disable */
// tslint:disable

import AbilityPassive from './ability_passive'
import PokemonBase from './pokemon_base'
import StatPassive from './stat_passive'

interface PokemonMega {
  /**
   * @default 0
   */
  add_attack: number
  /**
   * @default 0
   */
  add_defense: number
  /**
   * @default 0
   */
  add_hp: number
  /**
   * @default 0
   */
  add_sp_attack: number
  /**
   * @default 0
   */
  add_sp_defense: number
  /**
   * @default 0
   */
  add_speed: number
  /**
   * @default nextval('pta_03.pokemon_mega_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'pokemon_mega_id'}
  mega_ability_passive: (AbilityPassive['id']) | null
  mega_stat_passive: (StatPassive['id']) | null
  pokemon_id: PokemonBase['id']
  prefix: (string) | null
  size_class: (string) | null
  suffix: (string) | null
  types: (Array<string | null>) | null
  weight_class: (string) | null
}
export default PokemonMega;

interface PokemonMega_InsertParameters {
  /**
   * @default 0
   */
  add_attack?: number
  /**
   * @default 0
   */
  add_defense?: number
  /**
   * @default 0
   */
  add_hp?: number
  /**
   * @default 0
   */
  add_sp_attack?: number
  /**
   * @default 0
   */
  add_sp_defense?: number
  /**
   * @default 0
   */
  add_speed?: number
  /**
   * @default nextval('pta_03.pokemon_mega_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'pokemon_mega_id'}
  mega_ability_passive?: (AbilityPassive['id']) | null
  mega_stat_passive?: (StatPassive['id']) | null
  pokemon_id: PokemonBase['id']
  prefix?: (string) | null
  size_class?: (string) | null
  suffix?: (string) | null
  types?: (Array<string | null>) | null
  weight_class?: (string) | null
}
export type {PokemonMega_InsertParameters}
