/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 1Iq4+amaxcBqEMiPa5DNnRKuN1eMJ14tD2Mr69aWjWBOcFvUXNrNMGJ0JtHKi1qn7Xi0xlgX6wdovHJNnN/E/A==
 */

/* eslint-disable */
// tslint:disable

import MoveData from './move_data'
import PokemonMega from './pokemon_mega'

interface PokemonMegaMoves {
  mega_id: PokemonMega['id']
  move_id: MoveData['id']
}
export default PokemonMegaMoves;

interface PokemonMegaMoves_InsertParameters {
  mega_id: PokemonMega['id']
  move_id: MoveData['id']
}
export type {PokemonMegaMoves_InsertParameters}
