/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: pA0eLcxoAzWToXWLT8eENU7wQtLGTNfpuPOZWlf2gkUDXMBv+9VJBkZaKS0NkL/YAJiOby024M6C5zt7+jso/w==
 */

/* eslint-disable */
// tslint:disable

import MoveData from './move_data'
import PokemonBase from './pokemon_base'

interface PokemonSignatureMoves {
  move_id: MoveData['id']
  pokemon_id: PokemonBase['id']
}
export default PokemonSignatureMoves;

interface PokemonSignatureMoves_InsertParameters {
  move_id: MoveData['id']
  pokemon_id: PokemonBase['id']
}
export type {PokemonSignatureMoves_InsertParameters}
