/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: vNclRUEhrqI3U6kXjxE0kv7bISFCjyhfu0s3eMAfEQblg5j0/yqCYXiwSMR1N7vaNnafTqH/sbCiKAyPOxe5Tw==
 */

/* eslint-disable */
// tslint:disable

interface StatPassive {
  accuracy: (number) | null
  attack: (number) | null
  book: string
  defense: (number) | null
  /**
   * @default nextval('pta_03.stat_passive_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'stat_passive_id'}
  name: string
  page_num: number
  sp_attack: (number) | null
  sp_defense: (number) | null
  speed: (number) | null
}
export default StatPassive;

interface StatPassive_InsertParameters {
  accuracy?: (number) | null
  attack?: (number) | null
  book: string
  defense?: (number) | null
  /**
   * @default nextval('pta_03.stat_passive_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'stat_passive_id'}
  name: string
  page_num: number
  sp_attack?: (number) | null
  sp_defense?: (number) | null
  speed?: (number) | null
}
export type {StatPassive_InsertParameters}
