/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: Wbyhr2XAx7AuCcAoot1G0ehWxbMEZKLp4yWy8aaG4tF++JunAu1wvfNjgZlcYZZCmJjNUwvHa8OkPBxuMfHcwg==
 */

/* eslint-disable */
// tslint:disable

interface Amenity {
  embed: any
  id: string & {readonly __brand?: 'amenity_id'}
}
export default Amenity;

interface Amenity_InsertParameters {
  embed: any
  id: string & {readonly __brand?: 'amenity_id'}
}
export type {Amenity_InsertParameters}
