/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 41yQ8k4eDucwNu732Xms094od4/9nOYp5ih73BospePfJaHpq4TGuaHSZpD3mIuj0TIoKZOu1ki+KwR2EFHNWw==
 */

/* eslint-disable */
// tslint:disable

interface Basic {
  embed: any
  id: string & {readonly __brand?: 'basic_id'}
}
export default Basic;

interface Basic_InsertParameters {
  embed: any
  id: string & {readonly __brand?: 'basic_id'}
}
export type {Basic_InsertParameters}
