/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: DCw1967cNu91QhZkk90B6tfn60N4/3LaqCjQlu55qCSRC07sdtmQ/VSYsc441JtGxhSPBkzIaQ34q+BdFGvvLA==
 */

/* eslint-disable */
// tslint:disable

interface Building {
  embed: any
  id: string & {readonly __brand?: 'building_id'}
}
export default Building;

interface Building_InsertParameters {
  embed: any
  id: string & {readonly __brand?: 'building_id'}
}
export type {Building_InsertParameters}
