/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: YDo/nRy8ogiXdMPPt8egcY3Q8adxYDOs8eziz8F9KdJL4oOYjuMDJc1enYT3DuAigTj//0HfjU7zcNMcBGnyIQ==
 */

/* eslint-disable */
// tslint:disable

interface Enchantment {
  embed: any
  id: string & {readonly __brand?: 'enchantment_id'}
}
export default Enchantment;

interface Enchantment_InsertParameters {
  embed: any
  id: string & {readonly __brand?: 'enchantment_id'}
}
export type {Enchantment_InsertParameters}
