/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 8bsxwAUxIIatnbcIb6NU2oFnYuyntTuixqDI8VftiGf56+j/M3AiaKS5oE6lB5vBXKGQiyYVx7nEhM/FsFoFsA==
 */

/* eslint-disable */
// tslint:disable

interface Feats {
  embed: any
  id: string & {readonly __brand?: 'feats_id'}
}
export default Feats;

interface Feats_InsertParameters {
  embed: any
  id: string & {readonly __brand?: 'feats_id'}
}
export type {Feats_InsertParameters}
