/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 8BJVcqNUfVUQFGPPildE4pHG79xzm3Wl/oY5WbkIrPAKd2LRv0OsG6WiIm57/aooQu/xDZo0GzkLVY1bmysQQQ==
 */

/* eslint-disable */
// tslint:disable

interface Items {
  embed: any
  id: string & {readonly __brand?: 'items_id'}
}
export default Items;

interface Items_InsertParameters {
  embed: any
  id: string & {readonly __brand?: 'items_id'}
}
export type {Items_InsertParameters}
