/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: nvCp5kR9aB2Ek0r/lISSoYOHw6L/rJY5ZO0bjZvR0fy+1YvbrzRsvOlH+fVQZqXRIhQGVcMn02naO5gCB1SWQQ==
 */

/* eslint-disable */
// tslint:disable

interface List {
  embed: any
  id: string & {readonly __brand?: 'list_id'}
}
export default List;

interface List_InsertParameters {
  embed: any
  id: string & {readonly __brand?: 'list_id'}
}
export type {List_InsertParameters}
