/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: lDXb1XkE1e9VwEn5dkFN9YjalXiwMdfdW/8mu3XuO4Yd/SlJgaFUDsBOp7KbyNug4AeyvNc0gLlXMYuQIXDI+A==
 */

/* eslint-disable */
// tslint:disable

interface Maneuvers {
  embed: any
  id: string & {readonly __brand?: 'maneuvers_id'}
}
export default Maneuvers;

interface Maneuvers_InsertParameters {
  embed: any
  id: string & {readonly __brand?: 'maneuvers_id'}
}
export type {Maneuvers_InsertParameters}
