/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: P5mea9fDXLr/sjjkG5zrmTLgArSEW5B7QBhD/L4WDRFFnSKo0odZG5EC4+3mTDa7LDWr7hXsmfqT54N3nIhR2g==
 */

/* eslint-disable */
// tslint:disable

interface Song {
  embed: any
  id: string & {readonly __brand?: 'song_id'}
}
export default Song;

interface Song_InsertParameters {
  embed: any
  id: string & {readonly __brand?: 'song_id'}
}
export type {Song_InsertParameters}
