/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: EVKy4wXI6YBz3OdAWtcK3zbV5V23oiuAa5Zz0VNJ1mvxVKXA1pKihKWavFk8Sap5UVbxDyPqkJyFIsr7ffDn9A==
 */

/* eslint-disable */
// tslint:disable

interface Spells {
  embed: any
  id: string & {readonly __brand?: 'spells_id'}
}
export default Spells;

interface Spells_InsertParameters {
  embed: any
  id: string & {readonly __brand?: 'spells_id'}
}
export type {Spells_InsertParameters}
