/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: pGzfiRMdrHHf+kdIzINgEdjFMOpG1cDr/thWEyGNMERKJ2r1h1cVQssLNF8SsmZBn8coUq5f2ZaVCJ7JucGxDw==
 */

/* eslint-disable */
// tslint:disable

interface Status {
  embed: any
  id: string & {readonly __brand?: 'status_id'}
}
export default Status;

interface Status_InsertParameters {
  embed: any
  id: string & {readonly __brand?: 'status_id'}
}
export type {Status_InsertParameters}
