/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: KgTIr0rbIVVbV6RLPO9bBX9PGPMt2n8Z2izt0/ZMSblQdMsA9peMGJTNZy9wC4v7C4DX4Z4psjK+zMSS0jaopw==
 */

/* eslint-disable */
// tslint:disable

interface Techs {
  embed: any
  id: string & {readonly __brand?: 'techs_id'}
}
export default Techs;

interface Techs_InsertParameters {
  embed: any
  id: string & {readonly __brand?: 'techs_id'}
}
export type {Techs_InsertParameters}
