/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: F7AMxnNomIMnxj9VfXwVDjNr+hmpmj2f+4euRCypjE+/epmjwTnL90dIaRWVZjlBFBqGFws6AjmeuCahpuPnxw==
 */

/* eslint-disable */
// tslint:disable

interface Terrain {
  embed: any
  id: string & {readonly __brand?: 'terrain_id'}
}
export default Terrain;

interface Terrain_InsertParameters {
  embed: any
  id: string & {readonly __brand?: 'terrain_id'}
}
export type {Terrain_InsertParameters}
