/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 8fTtED7eusFUqo/0OQ9rvROgJ7XVdhcJuBDusgqrdc3svqYeXvh3c5e+2sUvbWrkAj2isSdcZjGTxutHCD1HHw==
 */

/* eslint-disable */
// tslint:disable

interface Weather {
  embed: any
  id: string & {readonly __brand?: 'weather_id'}
}
export default Weather;

interface Weather_InsertParameters {
  embed: any
  id: string & {readonly __brand?: 'weather_id'}
}
export type {Weather_InsertParameters}
