/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: WNCNGS5mVJMvdtyai9lTC8LKqKGHHMTt2d3HGmsX0La3ouOsXnENIbP+NnuPvs4ZKKj3kHohV4QBGXT6RPQ2JA==
 */

/* eslint-disable */
// tslint:disable

interface Class {
  embed: any
  id: string & {readonly __brand?: 'class_id'}
}
export default Class;

interface Class_InsertParameters {
  embed: any
  id: string & {readonly __brand?: 'class_id'}
}
export type {Class_InsertParameters}
