/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: NpZpDvOdXcz2ClWWW9STVvy9TuhEfNROkbavMnJIut5438ncUoLPa3XdYG+5H/hJaBP/XqGAb3RMdHw4k3PLjQ==
 */

/* eslint-disable */
// tslint:disable

interface Equip {
  embed: any
  id: string & {readonly __brand?: 'equip_id'}
}
export default Equip;

interface Equip_InsertParameters {
  embed: any
  id: string & {readonly __brand?: 'equip_id'}
}
export type {Equip_InsertParameters}
