/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: bmByzg8zYUyTEjK12Bl/5kr/b0X0oe0yQiz+RHauyTcsOtSqhhPFsXgJPGQkGCfuzVGolgzIfRUeOCUlljVbaA==
 */

/* eslint-disable */
// tslint:disable

interface Feat {
  embed: any
  id: string & {readonly __brand?: 'feat_id'}
}
export default Feat;

interface Feat_InsertParameters {
  embed: any
  id: string & {readonly __brand?: 'feat_id'}
}
export type {Feat_InsertParameters}
