/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: ruFLOM716ZRSMFHc2y3evqBQ4W24Qc7Z7gxYn36ESepPTQN4SL1rsBY4xDIpF2kWhRcUXFWgKe8Ye7LakVwKXw==
 */

/* eslint-disable */
// tslint:disable

interface Other {
  embed: any
  id: string & {readonly __brand?: 'other_id'}
}
export default Other;

interface Other_InsertParameters {
  embed: any
  id: string & {readonly __brand?: 'other_id'}
}
export type {Other_InsertParameters}
