/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: ZGIaTzc0/HHF/IUROR2TlWYUnpN6Twbor0xu7RDqV6qzYrEbODNVrgukZUfOeFv3JTlGsn/2bVhiI25BRyLJEg==
 */

/* eslint-disable */
// tslint:disable

interface Race {
  embed: any
  id: string & {readonly __brand?: 'race_id'}
}
export default Race;

interface Race_InsertParameters {
  embed: any
  id: string & {readonly __brand?: 'race_id'}
}
export type {Race_InsertParameters}
