/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: isqcsSBwlJTzPr12ISXxtxcRfkEK78onE8rB3L/yN7Sc7oEFiJuNAtamID+4YCPkm1VWySegUoSqgq19iw6Kaw==
 */

/* eslint-disable */
// tslint:disable

interface Rule {
  embed: any
  id: string & {readonly __brand?: 'rule_id'}
}
export default Rule;

interface Rule_InsertParameters {
  embed: any
  id: string & {readonly __brand?: 'rule_id'}
}
export type {Rule_InsertParameters}
