/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: DPzVEUVAHfupK46PGqrde3jMyuf2zilBy1VVY88VU6f5h6Tl7AxOGBHLEM66quulNzAC34/W8AUcza00K8KQeg==
 */

/* eslint-disable */
// tslint:disable

interface Spell {
  embed: any
  id: string & {readonly __brand?: 'spell_id'}
}
export default Spell;

interface Spell_InsertParameters {
  embed: any
  id: string & {readonly __brand?: 'spell_id'}
}
export type {Spell_InsertParameters}
